import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNavbar from "@/components/sub/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const drawerWidth = 240;

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
    </head>
    <body className={inter.className}>
    <div style={{ display: 'flex' }}>
      <SideNavbar />
      <main style={{ flexGrow: 1, padding: '24px', marginLeft: `${drawerWidth}px`, width: `calc(100% - ${drawerWidth}px)` }}>
        {children}
      </main>
    </div>
    </body>
    </html>
  );
}
