name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run Docker Compose services
        run: docker-compose -f docker-compose.yaml up --build -d

      - name: Wait for services to be healthy
        run: docker-compose -f docker-compose.yaml ps
        continue-on-error: true

      - name: Shut down Docker Compose services
        if: always()
        run: docker-compose -f docker-compose.yaml down

      - name: Ensure tests passed
        if: failure()
        run: exit 1
